### ISSUE TITLE
Extra slash "/" at end of request url 

### ISSUE THREAD

**Issue by farruxx** [infinitered/reactotron#804] opened 2018-09-03 11:21 UTC
While working with django server, it is important last "/" . 
App always show it, even if it doesn't exist

expected: http://example.com
actual: http://example.com/

**Comment by rmevans9** [comment] 2018-09-03 23:17
Hello @farruxx, I am sorry but I am not sure I follow what the issue is here? Can you maybe show me some screenshots from within Reactotron to show what you are having an issue with?

**Comment by skellock** [comment] 2018-09-04 13:20
Hmm... i don't see anywhere in the code where we add that... are you using [apisauce](https://github.com/infinitered/apisauce) to make the request?

**Comment by farruxx** [comment] 2018-09-04 13:28
Yes, I am using apisauce. Server's response differed when I change the url, may be apisauce makes correct request and incorrect url logging

**Comment by skellock** [comment] 2018-09-04 13:42
Following this backwards:

* [display](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Commands/ApiResponseCommand.js#L131)
* [component router](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Commands/index.js#L26)
* [state](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-app/App/Stores/SessionStore.js#L221)
* [server router](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-server/src/reactotron-core-server.ts#L237)
* [post request in mobile app](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-react-native/src/plugins/networking.js#L71) if you're not using `reactotron-apisauce` or [transform](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-core-client/src/plugins/api-response.ts) and [transport](https://github.com/infinitered/reactotron/blob/master/packages/reactotron-apisauce/src/index.js#L19) if you are
* [calling axios from apisauce](https://github.com/infinitered/apisauce/blob/master/lib/apisauce.ts#L204-L213)

Nothing I see here has that slash.

From the 2 graphics you've pasted, it totally looks like a bug on our end, I just don't know where!

**Comment by markrickert** [comment] 2024-01-24 00:12
I tested this in the latest version 3.x of the reactotron app. I used urls with and without that trailing slash and it appears to be showing correctly in more recent versions of reactotron. Closing this issue.

![Screenshot 2024-01-23 at 5 11 33 PM](https://github.com/infinitered/reactotron/assets/139261/3f77bdb4-77df-4e07-9ba9-4808790cad7b)

**Closed by markrickert** 2024-01-24 00:12 UTC
Labels: help wanted :wave:, bug :beetle:
