### ISSUE TITLE
Erratic State screen - stays blank after adding old state/stores

### ISSUE THREAD

**Issue by petermjones** [infinitered/reactotron#1121] opened 2019-08-09 17:43 UTC
When starting the new version, the State screen was blank.  Initially I re-tried entering the state/stores that should have been there from the previous version (updated an hour or so ago), and nothing happened.  It was only when I added a third store that wasn't there before that the screen updated and showed everything.  Quitting and restarting Reactotron did nothing.

1. States: auth, coupon
2. Update Reactotron
3. States: (none)
4. Add state 'auth'
5. States: (none)
6. Add state 'coupon'
7. States: (none)
8. Add state 'user'
9. States: auth, coupon, user

**Comment by petermjones** [comment] 2019-08-30 17:11
It does not happen very often at all, but it did immediately upon updating my version of Reactotron on the date I created the issue.  Basically the State screen stayed blank until it felt that there was something new to draw, in this case the 'user' state.  So, what stops the State screen from rendering anything (aside from add a new state)?

**Comment by markrickert** [comment] 2024-01-24 01:56
I'm closing this for now. Please feel free to reopen if you can give us some more feedback and if the issue is still present in the latest version of reactotron!

**Closed by markrickert** 2024-01-24 01:56 UTC
