### ISSUE TITLE
Reactotron turning white when I try to see details of connections

### ISSUE THREAD

**Issue by AilsonFreire** [infinitered/reactotron#1007] opened 2019-04-25 13:18 UTC
![Captura de Tela 2019-04-25 às 10 11 44](https://user-images.githubusercontent.com/9551815/56738477-15ef8800-6743-11e9-83b3-e2a4b2a54c72.png)

I'm using Mac mini 2014, 1,4 GHz Intel Core i5, 4 GB 1600 MHz DDR3 e
reactotron-react-native: 3.2.2

**Comment by rmevans9** [comment] 2019-04-25 16:26
Interesting. Seems like reactotron is crashing on you. When you say try to see the details of connections does that mean hitting the home tab or expanding the little bottom tray to switch connections?

**Comment by SteffanUA** [comment] 2019-04-26 17:32
Similar issue here on windows. I'm using a windows 10 machine with the latest Reactotron Desktop build

**Comment by AilsonFreire** [comment] 2019-04-30 11:11
This happens when I am in timeline tab. This list all my connections but, when I try to see details of its responses, the app turns all blank.

**Comment by Fl4zher** [comment] 2019-04-30 16:50
Same on win10

**Comment by rmevans9** [comment] 2019-05-01 02:06
@AilsonFreire Please do me a favor - Find a way to cause the issue. When there is a timeline item that if you were to click that would cause a crash in the list, instead of clicking on it click the giant down arrow in the top right of the window and select a location. Upload that file here. If the events contain information you don't want to make public please let me know and I can provide alternative ways to get it to me.

@Fl4zher and @SteffanUA are you trying to expand a item when this occurs on Windows too?

**Comment by faizalshap** [comment] 2019-05-01 05:05
same for me as well

**Comment by arikpre** [comment] 2019-05-01 07:11
Same, since updating to Reactotron 2.13.0 (Osx 10.14.4)

Crashes whenever I try to see the details in the timeline

**Comment by rmevans9** [comment] 2019-05-01 09:58
Oh no! I’ll look at this here in a couple of hours. What kind of item did you try and expand?

**Comment by arikpre** [comment] 2019-05-01 10:21
Hard to pinpoint exactly now that I reverted to 2.12.0, but if I recall clearly it did in on any debug.

For the record I did channel regular console.logs to reactotron with => console.log = Reactotron.log;

I don't know if this might be a parameter...

**Comment by rmevans9** [comment] 2019-05-01 11:39
@arikpre I have found the issue and have a build running. The root cause here was the fact that I accidentally removed a needed import. The version will be 2.13.1 when it finishes building (~10 minutes or so)

**Comment by arikpre** [comment] 2019-05-01 12:11
@rmevans9 Fixed! Works like a charm!

Btw, just wanna know if there is a possibility to customize the color of the tag in Reactotron.display and also if it would be possible to filter displays based on the name property or (event the color, if I may).

The reason for this is that I like to create categories of logs but don't want to be overloaded with them visually, so this would help a lot.

Anyway thanks a lot, it's a great great tool!

**Comment by rmevans9** [comment] 2019-05-01 12:13
@arikpre There is not currently the possibility of doing this but if you open an issue about this and describe how you would want something like this to work we can certainly take it into consideration.

@faizalshap @Fl4zher @AilsonFreire The above fix likely doesn't fix the issue you guys are having as you started seeing this before the broken version was released so I am interested in the export of the timeline when any of you get a chance.

**Comment by Fl4zher** [comment] 2019-05-01 20:03
@rmevans9 Seems like the problem is fixed!

**Comment by ioveracker** [comment] 2019-05-02 06:37
FWIW I just started seeing this with 2.13.0 and it was fixed on update of the Reactotron client. 👌

**Comment by AilsonFreire** [comment] 2019-05-02 12:17
I uninstalled the .dmg version and installed using brew cash in my Mac, this version worked fine for me.

**Comment by rmevans9** [comment] 2019-05-17 02:38
It seems like this is working well. Closing this issue 👍

**Closed by rmevans9** 2019-05-17 02:38 UTC

**Comment by RaulCorreia** [comment] 2019-05-24 12:53
Hello, I'm sorry to reopen this problem, but when I use the Reactotron.display function the screen goes white, but using the same text in Reactotron.log or Reactotron.logImportant works perfectly, I'm using version 2.14.2.

**Comment by RaulCorreia** [comment] 2019-05-24 12:55
Hello, when I use the Reactotron.display function the screen goes white, but using the same text in Reactotron.log or Reactotron.logImportant works perfectly, I'm using version 2.14.2.

**Comment by rmevans9** [comment] 2019-05-24 12:59
@RaulCorreia Can you show me the code you are trying to call display with? Specifically wanting to know the data that is being passed to Reactotron

**Comment by RaulCorreia** [comment] 2019-05-27 12:52
> @RaulCorreia Can you show me the code you are trying to call display with? Specifically wanting to know the data that is being passed to Reactotron

sorry for the delay, basically any json I send, like 
{type: UNSUBSCRIBE, payload: true} in Reducer

**Comment by rmevans9** [comment] 2019-05-27 18:20
@RaulCorreia Could you show me the `Reactotron.display` call specifically? I would like to use that to try and reproduce the error

**Comment by RaulCorreia** [comment] 2019-05-27 18:43
> @RaulCorreia Could you show me the `Reactotron.display` call specifically? I would like to use that to try and reproduce the error

I use it that way

Reactotron.display({
            name: 'Reducer',
            value: action,
            preview: action,
            important: true,
        })

'action' is my json arriving at reduer.
the first json it should display is {type@@redux/INIT}
but it does not show anything, just the white screen, if I use only the Reactotron.log(action) it displays everything perfectly

**Comment by rmevans9** [comment] 2019-05-27 20:37
@RaulCorreia The issue is `preview` is expected to be a string. We could probably do better of calling that out and making that known. Perhaps you would like to write up an issue indicating that we should handle failures from passing an object to `preview` better?

**Comment by RaulCorreia** [comment] 2019-05-27 20:52
> @RaulCorreia The issue is `preview` is expected to be a string. We could probably do better of calling that out and making that known. Perhaps you would like to write up an issue indicating that we should handle failures from passing an object to `preview` better?

after you've talked about being a string in the preview I used JSON.stringify() only in the preview and it worked, so I guess Log should do the same
